#!/bin/bash
cd ~/github/remotion-claw/podcast-ep2

edge-tts --voice "en-US-GuyNeural" --text "And I'm Alex. This week we're talking about the biggest security release OpenClaw has ever shipped." --write-media a1.mp3 && echo "✓ a1"
edge-tts --voice "en-US-GuyNeural" --text "Ten. That's not a typo. Let's break them down because some of these are genuinely scary." --write-media a2.mp3 && echo "✓ a2"
edge-tts --voice "en-US-GuyNeural" --text "So basically, you visit a malicious website, and it could connect to your OpenClaw gateway pretending to be you." --write-media a3.mp3 && echo "✓ a3"
edge-tts --voice "en-US-GuyNeural" --text "What about the workspace plugin auto-load one? That sounds bad." --write-media a4.mp3 && echo "✓ a4"
edge-tts --voice "en-US-GuyNeural" --text "So just cloning a GitHub repo could give someone code execution on your machine." --write-media a5.mp3 && echo "✓ a5"
edge-tts --voice "en-US-GuyNeural" --text "There were also two Unicode-related exploits, right?" --write-media a6.mp3 && echo "✓ a6"
edge-tts --voice "en-US-GuyNeural" --text "So an agent asks you to approve a command, but the command you see isn't what actually runs." --write-media a7.mp3 && echo "✓ a7"
edge-tts --voice "en-US-GuyNeural" --text "Let's talk about the other side of this release. There were some big features too." --write-media a8.mp3 && echo "✓ a8"
edge-tts --voice "en-US-GuyNeural" --text "No more separate browser profiles. No more logging into everything twice. Just attach to Chrome and go." --write-media a9.mp3 && echo "✓ a9"
edge-tts --voice "en-US-GuyNeural" --text "That's powerful but also kind of terrifying from a security perspective." --write-media a10.mp3 && echo "✓ a10"
edge-tts --voice "en-US-GuyNeural" --text "Makes sense. What about the Dashboard v2 rebuild?" --write-media a11.mp3 && echo "✓ a11"
edge-tts --voice "en-US-GuyNeural" --text "The old dashboard was pretty rough. Just a basic status page basically." --write-media a12.mp3 && echo "✓ a12"
edge-tts --voice "en-US-GuyNeural" --text "Speaking of fleets, the Android app had a massive month too." --write-media a13.mp3 && echo "✓ a13"
edge-tts --voice "en-US-GuyNeural" --text "Your phone is basically becoming a full sensor node for your agent fleet." --write-media a14.mp3 && echo "✓ a14"
edge-tts --voice "en-US-GuyNeural" --text "The motion and pedometer data is interesting. Health tracking through your agent?" --write-media a15.mp3 && echo "✓ a15"
edge-tts --voice "en-US-GuyNeural" --text "Smart. What about the breaking changes? There were four in the beta release." --write-media a16.mp3 && echo "✓ a16"
edge-tts --voice "en-US-GuyNeural" --text "That's actually a good security move. Most users probably don't need shell access from their chat agent." --write-media a17.mp3 && echo "✓ a17"
edge-tts --voice "en-US-GuyNeural" --text "So the philosophy is restrict dangerous tools but enable orchestration." --write-media a18.mp3 && echo "✓ a18"
edge-tts --voice "en-US-GuyNeural" --text "Plugin authors are going to love that." --write-media a19.mp3 && echo "✓ a19"
edge-tts --voice "en-US-GuyNeural" --text "Let's talk about multimodal memory. Images and audio can be indexed now?" --write-media a20.mp3 && echo "✓ a20"
edge-tts --voice "en-US-GuyNeural" --text "That's the kind of feature that sounds small but changes how you use the whole system." --write-media a21.mp3 && echo "✓ a21"
edge-tts --voice "en-US-GuyNeural" --text "Or searching through voice notes by topic instead of scrolling through a list of timestamps." --write-media a22.mp3 && echo "✓ a22"
edge-tts --voice "en-US-GuyNeural" --text "What does it actually do?" --write-media a23.mp3 && echo "✓ a23"
edge-tts --voice "en-US-GuyNeural" --text "So in a multi-agent pipeline, the coordinator doesn't waste tokens processing stuff it's already delegated." --write-media a24.mp3 && echo "✓ a24"
edge-tts --voice "en-US-GuyNeural" --text "One more thing before we wrap. The Ollama reasoning model fix." --write-media a25.mp3 && echo "✓ a25"
edge-tts --voice "en-US-GuyNeural" --text "That's embarrassing for the model and confusing for the user." --write-media a26.mp3 && echo "✓ a26"
edge-tts --voice "en-US-GuyNeural" --text "Alright, that's the rundown. Ten CVEs, a dashboard rebuild, Chrome attach mode, multimodal memory, Android velocity, and a bunch of breaking changes." --write-media a27.mp3 && echo "✓ a27"
edge-tts --voice "en-US-GuyNeural" --text "Next week we're diving into Kubernetes deployment and fleet scaling. Until then, keep your agents patched." --write-media a28.mp3 && echo "✓ a28"
echo "ALL ALEX DONE"
