#!/bin/bash
cd ~/github/remotion-claw/podcast-ep2

rclaw tts "Welcome back to The OpenClaw Weekly. I'm CyperX." --output c1.wav --seed 1337 && echo "✓ c1"
rclaw tts "Version twenty twenty six dot three dot twelve dropped with ten CVEs patched in a single release." --output c2.wav --seed 1337 && echo "✓ c2"
rclaw tts "The headliner is cross-site WebSocket hijacking." --output c3a.wav --seed 1337 && echo "✓ c3a"
rclaw tts "If you were running in trusted proxy mode, an attacker could hijack your WebSocket connection from a different browser tab." --output c3b.wav --seed 1337 && echo "✓ c3b"
rclaw tts "Exactly. The fix enforces browser origin validation on all WebSocket upgrades." --output c4a.wav --seed 1337 && echo "✓ c4a"
rclaw tts "Should have been there from day one honestly." --output c4b.wav --seed 1337 && echo "✓ c4b"
rclaw tts "That one is nasty. If you cloned a repo that had a malicious OpenClaw plugin in it, it would auto-load and execute code without asking you." --output c5.wav --seed 1337 && echo "✓ c5"
rclaw tts "Yep. Now workspace plugins require an explicit trust decision before they load. Much safer." --output c6.wav --seed 1337 && echo "✓ c6"
rclaw tts "Yeah, zero-width characters and fullwidth characters. Both could be used to spoof exec approval prompts." --output c7.wav --seed 1337 && echo "✓ c7"
rclaw tts "Right. Invisible characters hiding in the command text." --output c8a.wav --seed 1337 && echo "✓ c8a"
rclaw tts "The fix now strips and detects those patterns before showing you the approval prompt." --output c8b.wav --seed 1337 && echo "✓ c8b"
rclaw tts "The browser attach mode is the one I'm most excited about." --output c9a.wav --seed 1337 && echo "✓ c9a"
rclaw tts "Your agent can now connect to your actual signed-in Chrome session." --output c9b.wav --seed 1337 && echo "✓ c9b"
rclaw tts "Profile equals user and your agent has access to your Gmail, your GitHub, your Jira." --output c10a.wav --seed 1337 && echo "✓ c10a"
rclaw tts "Whatever you're logged into." --output c10b.wav --seed 1337 && echo "✓ c10b"
rclaw tts "Which is why it's behind an explicit profile flag and the session lifecycle is hardened. You have to opt in." --output c11.wav --seed 1337 && echo "✓ c11"
rclaw tts "Complete ground-up rewrite. Command palette like VS Code, mobile navigation tabs, search across sessions, pinned messages." --output c12a.wav --seed 1337 && echo "✓ c12a"
rclaw tts "It's a real web UI now." --output c12b.wav --seed 1337 && echo "✓ c12b"
rclaw tts "Now it's modular. You've got overview, chat, config, agents, and sessions as separate views." --output c13a.wav --seed 1337 && echo "✓ c13a"
rclaw tts "You can actually manage your fleet from a browser." --output c13b.wav --seed 1337 && echo "✓ c13b"
rclaw tts "Three releases in four weeks. Camera access, notification actions, contacts, calendar, motion and pedometer data." --output c14.wav --seed 1337 && echo "✓ c14"
rclaw tts "That's exactly the idea. Your agent can read your notifications, reply to them, check your calendar." --output c15a.wav --seed 1337 && echo "✓ c15a"
rclaw tts "Even see if you're walking or sitting." --output c15b.wav --seed 1337 && echo "✓ c15b"
rclaw tts "Could be. Or just context awareness. Your agent knows you're on a run so it holds non-urgent notifications." --output c16.wav --seed 1337 && echo "✓ c16"
rclaw tts "The big one is tools dot profile defaulting to messaging." --output c17a.wav --seed 1337 && echo "✓ c17a"
rclaw tts "New installs no longer get coding and system tools turned on by default." --output c17b.wav --seed 1337 && echo "✓ c17b"
rclaw tts "Agreed. And ACP dispatch is now enabled by default, which is the opposite direction." --output c18a.wav --seed 1337 && echo "✓ c18a"
rclaw tts "They're making agent-to-agent communication the default." --output c18b.wav --seed 1337 && echo "✓ c18b"
rclaw tts "Exactly. Also the Plugin SDK had a breaking change. The HTTP handler API was redesigned completely." --output c19.wav --seed 1337 && echo "✓ c19"
rclaw tts "Ha. Yeah. But the new API is cleaner. Explicit route registration with path, auth, and match parameters." --output c20.wav --seed 1337 && echo "✓ c20"
rclaw tts "Using Gemini embedding two preview. You can point it at a folder of screenshots or voice memos and your agent can semantically search through them." --output c21.wav --seed 1337 && echo "✓ c21"
rclaw tts "Totally. Imagine asking your agent what did I screenshot last week about that API design. And it actually finds it." --output c22.wav --seed 1337 && echo "✓ c22"
rclaw tts "It lets an orchestrator agent end its turn immediately instead of waiting for all queued tool calls to finish." --output c24a.wav --seed 1337 && echo "✓ c24a"
rclaw tts "And it can pass a hidden payload to the next turn." --output c24b.wav --seed 1337 && echo "✓ c24b"
rclaw tts "Right. It's an efficiency primitive. Saves compute and makes agent handoffs cleaner." --output c25.wav --seed 1337 && echo "✓ c25"
rclaw tts "Local reasoning models were leaking their internal think blocks into user-visible replies." --output c26a.wav --seed 1337 && echo "✓ c26a"
rclaw tts "Like you'd see the model's internal monologue mixed into the actual response." --output c26b.wav --seed 1337 && echo "✓ c26b"
rclaw tts "Fixed now. The think tags are properly stripped before the response is delivered." --output c27.wav --seed 1337 && echo "✓ c27"
rclaw tts "If you're self-hosting OpenClaw, update to three dot thirteen. Seriously. Those security patches alone are worth it." --output c28.wav --seed 1337 && echo "✓ c28"
rclaw tts "See you next week." --output c29.wav --seed 1337 && echo "✓ c29"
echo "ALL CYPERX DONE"
